import type { GetServerSideProps, NextPage } from "next";
import axios from "axios";
import Head from "next/head";

const Home: NextPage = (props) => {
  console.log({ props });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className="text-red-500">Tailwind</h2>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data } = await axios.get(
    "https://menus.flipdish.co/prod/16798/e6220da2-c34a-4ea2-bb51-a3e190fc5f08.json"
  );

  console.log(data);

  return {
    props: {
      chicken: "dinner",
    },
  };
};
