import type { GetServerSideProps, NextPage } from "next";
import axios from "axios";
import Head from "next/head";

import { Menu } from "../types";
import Image from "next/image";

type Props = {
  menuData: Menu;
};

const Home: NextPage<Props> = ({ menuData }) => {
  return (
    <div>
      {/* Meta data */}
      <Head>
        <title>Foxtrot Delta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col p-4 items-center">
        <h2 className="mb-4 text-2xl font-bold text-fdBlue">Menu</h2>

        {/* List of sections */}
        <ul className="max-w-2xl">
          {menuData.MenuSections.map((section) => (
            <li className="mb-8" key={section.MenuSectionId}>
              <h2 className="font-bold text-xl mb-4 text-fdBlue">
                {section.Name}
              </h2>

              {/* List of menu items */}
              {section.MenuItems.map((menuItem) => {
                const { Price, PublicId, Name, Description, ImageUrl } =
                  menuItem;

                const formattedPrice = new Intl.NumberFormat(undefined, {
                  style: "currency",
                  currency: "GBP",
                }).format(Price);

                return (
                  <div
                    key={PublicId}
                    className="grid items-center gap-x-4 border-b py-4 px-2 cursor-pointer hover:shadow rounded"
                    style={{ gridTemplateColumns: "1fr max-content" }}
                  >
                    <p className="col-start-1 row-start-1 font-bold">{Name}</p>
                    <p className="col-start-1 row-start-2">{Description}</p>
                    <p className="col-start-1 row-start-3">{formattedPrice}</p>
                    {ImageUrl && (
                      <div className="relative flex col-start-2 row-start-1 row-end-4 rounded overflow-hidden">
                        <Image
                          src={ImageUrl}
                          alt={Description}
                          layout="fixed"
                          width="100"
                          height="100"
                          objectFit="cover"
                        />
                      </div>
                    )}
                  </div>
                );
              })}
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;

// Server Side Rendering
export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data } = await axios.get<Menu>(
    "https://menus.flipdish.co/prod/16798/e6220da2-c34a-4ea2-bb51-a3e190fc5f08.json"
  );

  return {
    props: {
      menuData: data,
    },
  };
};
