import type { GetServerSideProps, NextPage } from "next";
import axios from "axios";
import Head from "next/head";

import { Menu } from "../types";
import Image from "next/image";

type Props = {
  menuData: Menu;
};

const Home: NextPage<Props> = ({ menuData }) => {
  console.log(menuData);

  return (
    <div>
      <Head>
        <title>Foxtrot Delta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className="text-red-500">Tailwind</h2>

        <ul>
          {menuData.MenuSections.map((section) => (
            <li className="border border-blue-500" key={section.MenuSectionId}>
              <h2>{section.Name}</h2>
              {section.MenuItems.map((menuItem) => (
                <>
                  <p key={menuItem.PublicId}>{menuItem.Name}</p>
                  {menuItem.ImageUrl && (
                    <Image
                      src={menuItem.ImageUrl}
                      alt={menuItem.Description}
                      width="100"
                      height="100"
                    />
                  )}
                </>
              ))}
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data } = await axios.get<Menu>(
    "https://menus.flipdish.co/prod/16798/e6220da2-c34a-4ea2-bb51-a3e190fc5f08.json"
  );

  return {
    props: {
      menuData: data,
    },
  };
};
